### ISSUE TITLE
Tracking issue: Penumbra-WebGPU foundations

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/webgpu#1]
**_Objective:_** Set up the WebGPU repository

- [x] Create new repo `penumbra/webgpu` with boilerplate.
     - [x] TypeScript configuration (`.tsconfig`)
     - [x] ESLint rules
     - [x] Prettier
- [x] https://github.com/penumbra-zone/webgpu/pull/5
Fork reference [demox-labs](https://github.com/demox-labs/webgpu-msm) repository, which will serve as the naive (**unoptimized**) WebGPU implementation, and strip unnecessary components.
