### ISSUE TITLE
Tracking issue: Proposal

### ISSUE THREAD

**Issue by TalDerei** [penumbra-zone/webgpu#2]
_**Proposed Work:**_ Implement a general-purpose, open-source WebGPU-based Groth16 prover to accelerate client-side proof generation for the Penumbra Protocol. 

**_Phases:_** The end-to-end WebGPU POC will comprise three distinct, high-level phases described in greater detail below. Generally, phase (**ii**) scopes the open-source gluing / integration of the Penumbra web-code with a WebGPU backend, and phase (**iii**) scopes the closed-source [zprize](https://www.zprize.io/) work based on a sparse-matrix MSM design ([cuZK](https://eprint.iacr.org/2022/1321.pdf)). Since (**iii**) is a single, sub-component in the larger system (**ii**) that can be built entirely independently and without conflict, then (**ii**) would be optimally structured to ease the eventual merging with (**iii**). For instance, hot-swapping the reference MSM algorithm in (**ii**) with the optimized MSM algorithm in (**iii**) using an API function call. Phases (**ii**) and (**iii**) would be concurrently built (in the open and closed-source), and remain independent until the codebases can be merged.

**Phase (I): Architecture Code and Performance Review** 
- [ ] **Description**: Conduct general architecture, code-review, and comprehensive performance pass comprising the scoped penumbra crates (arkworks groth16 prover, crypto-modules, [penumbra-web-assembly](https://github.com/penumbra-zone/penumbra/tree/main/crates/wasm)). This includes profiling and tracing the web-assembly execution and memory consumption to identify performance bottlenecks that lead to ~8x slowdown between native Rust-generated proof generation in the CLI ([PCLI](https://guide.penumbra.zone/main/pcli/install.html)) versus the WASM-generated code in the [browser-context](https://github.com/penumbra-zone/web). 
**Success:** Measured by successfully understanding the system architecture design (e.g. transaction planning, proof generation, storage, etc.) and properly identifying the performance bottlenecks. 

**Phase (II): WebGPU Backend for Penumbra Web Code**
- [ ] **Description**: Integration of the naive **(unoptimized)** WebGPU components with Penumbra WASM and web-client. The reference WebGPU MSM repository from [Demox-Labs](https://github.com/demox-labs/webgpu-msm/tree/main) will serve as the naive WebGPU implementation. 
**Success**: Measured by successfully generating a client-side proof (2^16 constraints) on the GPU. 
     - [ ] **1.** Build a typescript wrapper class to overwrite the WASM-based MSM calls in the commitment scheme with the WebGPU-version.
     - [ ] **2.** Build a general prover/verifier executable and typescript API connecting the WASM and WebGPU components for generating a Penumbra client-side proof. 
     - [ ] **3.** Determine any necessary changes to **(a)** Penumbra [WASM crate](https://github.com/penumbra-zone/penumbra/tree/main/crates/wasm) and **(b)** Eventual integration strategies with [web-code](https://github.com/penumbra-zone/web).
     - [ ] 4. Engage in an iterative process to determine what portion of the critical path logic / routines in the Groth16 Polynomial IOP should be implemented in WebGPU, if any. The objective is to identify what level of abstraction yields diminishing returns to performance besides putting the low-level helpers (ie. crypto library) and MSM scheme in WebGPU. 

- [ ] **Phase (III): ZPrize Competition Related-Work**
     - [ ] **Description**: Integration and adaptation of optimized WebGPU MSM with Penumbra WASM and web clients. As part of the Zprize submission collaboration, there will be a closed-source WebGPU MSM which will be open-sourced upon completion of the Zprize contest submission deadline (_Early February_). Upon open-sourcing, the optimized WebGPU MSM will be adapted and integrated into the Penumbra prover from phase (**ii**), swapping the new optimized MSM for the unoptimized MSM from the demox-labs repository. The MSM will be rewritten in typescript / WGSL (WebGPU shader language) and utilize web-workers for multi-threading, rather than using the existing variable-base MSM from Arkworks in the Penumbra [monorepo](https://github.com/penumbra-zone/penumbra). 
**Success**: Measured by achieving sub-second MSM execution times.

**Comment by TalDerei** [comment]
`Phase III` is currently a post-mainnet task
